name: Go
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test:
    runs-on: [windows-2019]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        make check
